spring:

#  jpa:
#    hibernate:
#      ddl-auto: validate
#    properties:
#      hibernate:
#        #show_sql: true
#        #dialect: net.postquantum.pqcore.user.dal.hibernate.postgresql.MyPostgreSQL9Dialect
#        dialect: net.postquantum.pqcore.user.dal.hibernate.postgresql.MyPostgreSQL9Dialect
#      org.hibernate.flushMode: COMMIT

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:localtestdatabase;MODE=MySQL

  jackson:
        property-naming-strategy: SNAKE_CASE